-- Seed af referencedata. Genereret fra belastning/data/*.json – ret JSON-filerne og kør scripts-generer-data.mjs.

insert into butikstyper (navn, salgsareal, lagerareal, ovrigtareal, kasser, sco, tilvalg) values
  ('Dagli’Brugsen', 690, 100, 60, 2, 1, ARRAY['deli','bakeoff','centralkoel','varmepumpe','flaskeautomat']),
  ('SuperBrugsen', 1100, 200, 120, 4, 2, ARRAY['deli','bakeoff','slagter','centralkoel','varmepumpe','flaskeautomat']),
  ('Kvickly', 2200, 400, 220, 6, 4, ARRAY['deli','bakeoff','slagter','centralkoel','varmepumpe','flaskeautomat','elevator']),
  ('365discount', 600, 90, 50, 2, 1, ARRAY['bakeoff','centralkoel','varmepumpe','flaskeautomat'])
on conflict (navn) do update set salgsareal=excluded.salgsareal, lagerareal=excluded.lagerareal, ovrigtareal=excluded.ovrigtareal, kasser=excluded.kasser, sco=excluded.sco, tilvalg=excluded.tilvalg;

insert into referencemaalinger (butik, salgsareal, peak_a, kilde) values
  ('SuperBrugsen Dragør (1013)', 1000, 130, 'Målt 15-min. peak'),
  ('Brugsen Søby, Ærø', 600, 110, 'Målt 15-min. peak'),
  ('Dagli’Brugsen Rask Mølle (projekt)', 688, 120, 'Målt 15-min. peak');

insert into katalog (id, navn, afdeling, rum, kategori, kw, spaending, cosphi, df, karakteristik, rcd, noedforsyning, bimaaler, varmeafgivelse, tavle, tilvalg, skalering_type, skalering_vaerdi, amp_datablad, leverandoer, plankoder, kilde, note) values
  ('BU2', 'Grøntvægt (F&G)', 'Salgslokale', 'salg', 'it', 0.5, 230, 0.95, 0.6, 'C', '30 mA A', false, false, 0.9, 'HT01', null, 'fast', 1, null, null, ARRAY['GRØNTVÆGT','F&G_BORD'], 'El-effektoversigt', null),
  ('BU3', 'Lys i inventar (CTS-styret)', 'Belysning', 'salg', 'lys', 0.2, 230, 1, 0.9, 'B', '30 mA A', false, false, 0.9, 'HT01', null, 'm2salg', 175, null, null, '{}', 'El-effektoversigt', 'Slukkes om natten via CTS'),
  ('BU5', 'Impulskølere plug-in', 'Køl & frost', 'salg', 'koel', 0.385, 230, 0.9, 0.85, 'C', '30 mA A', true, false, 0.6, 'HT01', null, 'm2salg', 58, null, null, ARRAY['EGM','LDF','CLS','IMPULS'], 'El-effektoversigt, skaleret', 'Kritisk – på nødforsyning'),
  ('BU9', 'Kaffemølle', 'Salgslokale', 'salg', 'maskine', 2.5, 400, 0.9, 0.3, 'C', '30 mA A', false, false, 0.4, 'HT01', null, 'fast', 1, null, null, ARRAY['KAFFEMØLLE'], 'El-effektoversigt', null),
  ('BU11', 'Tobaksskabe', 'Salgslokale', 'salg', 'stik', 0.15, 230, 0.95, 0.5, 'B', '30 mA A', false, false, 0.5, 'HT01', null, 'm2salg', 120, null, null, ARRAY['TOBAK','RYGEARTIKLER'], 'El-effektoversigt', null),
  ('BU14', 'Dispositionsstik salgsareal', 'Salgslokale', 'salg', 'stik', 0.2, 230, 0.9, 0.2, 'B', '30 mA A', false, false, 0.5, 'HT01', null, 'm2salg', 35, null, null, '{}', 'Referencetavle', null),
  ('BU15', 'POS-kasser + SCO', 'IT, POS & sikring', 'salg', 'it', 0.5, 230, 0.9, 0.9, 'B', '30 mA A', true, false, 0.9, 'HT01', null, 'kasser', null, null, null, ARRAY['KASSE','SCO','KASSELINJE'], 'Maskinliste POS', 'Kritisk – salg skal kunne gennemføres under nedbrud'),
  ('BU19', 'Tablets scan & betal', 'IT, POS & sikring', 'salg', 'it', 0.05, 230, 0.9, 0.9, 'B', '30 mA A', false, false, 0.9, 'HT01', null, 'fast', 3, null, null, '{}', 'El-effektoversigt', null),
  ('BU20', 'Udendørs 230/400 V stik (CEE foran butik)', 'Udvendigt', 'udv', 'stik', 3.6, 400, 0.9, 0.3, 'C', '30 mA A', false, true, 0, 'HT01', null, 'fast', 1, null, null, '{}', 'El-effektoversigt', null),
  ('BU22', 'Disponibelt 400 V stik ved port/lager', 'Lager & varemodtag.', 'lager', 'stik', 6, 400, 0.9, 0.3, 'C', '30 mA A', false, false, 0.5, 'HT01', null, 'fast', 1, null, null, '{}', 'El-effektoversigt', null),
  ('BU30', 'Frico AGS luftgardin', 'HVAC & varmepumper', 'teknik', 'hvac', 6, 400, 0.9, 0.5, 'C', '30 mA A', false, false, 0, 'HT01', null, 'fast', 1, null, null, '{}', 'Byggeprogram §11.4', null),
  ('BU31', 'Natrullegardin, motor', 'Salgslokale', 'salg', 'maskine', 0.15, 230, 0.9, 0.1, 'C', '30 mA A', false, false, 0, 'HT01', null, 'fast', 2, null, null, '{}', 'El-effektoversigt', null),
  ('BU32', 'Hurtigport lager/butik', 'Lager & varemodtag.', 'lager', 'maskine', 1.5, 400, 0.85, 0.2, 'C', '30 mA A', false, false, 0, 'HT01', null, 'fast', 1, null, null, ARRAY['HURTIGPORT'], 'El-effektoversigt', null),
  ('BU33', 'Automatiske skydedøre', 'Salgslokale', 'salg', 'maskine', 0.5, 230, 0.9, 0.4, 'C', '30 mA A', false, false, 0, 'HT01', null, 'fast', 1, null, null, ARRAY['SKYDEDØR'], 'Byggeprogram', null),
  ('BC1', 'Kasser bageri (EDB + alm.)', 'Deli', 'salg', 'it', 0.4, 230, 0.9, 0.9, 'B', '30 mA A', false, false, 0.9, 'HT01', 'deli', 'fast', 2, null, null, '{}', 'El-effektoversigt', null),
  ('BC4', 'Køledisk betjent', 'Deli', 'salg', 'koel', 1.2, 230, 0.9, 0.85, 'C', '30 mA A', true, false, 0.6, 'HT01', 'deli', 'fast', 2, null, null, ARRAY['BETJENT_DISK'], 'El-effektoversigt', null),
  ('BC5', 'Køledisk selvbetjent', 'Deli', 'salg', 'koel', 1.1, 230, 0.9, 0.85, 'C', '30 mA A', true, false, 0.6, 'HT01', 'deli', 'fast', 1, null, null, ARRAY['SELVBETJENT_DISK'], 'Marianne SB', null),
  ('BC7', 'Bake-off ovn 400 V', 'Brød & bake-off', 'salg', 'maskine', 5.8, 400, 0.95, 0.65, 'D', '30 mA A', false, false, 0.5, 'HT01', 'bakeoff', 'fast', 1, null, null, ARRAY['BAGEROVN'], 'Maskinliste POS', null),
  ('BC10', 'Brødskærer', 'Brød & bake-off', 'salg', 'maskine', 2.5, 400, 0.85, 0.4, 'C', '30 mA A', false, false, 0.4, 'HT01', 'bakeoff', 'fast', 1, null, null, '{}', 'Maskinliste POS', null),
  ('BC11', 'Kølebord bageri/deli', 'Deli', 'salg', 'koel', 1.4, 230, 0.9, 0.85, 'C', '30 mA A', true, false, 0.6, 'HT01', 'deli', 'fast', 1, null, null, '{}', 'Maskinliste POS', null),
  ('BC15', 'Kaffemaskine (fælles)', 'Brød & bake-off', 'salg', 'maskine', 3.1, 230, 0.95, 0.6, 'C', '30 mA A', false, false, 0.6, 'HT01', 'bakeoff', 'fast', 1, null, null, ARRAY['KAFFEMASKINE'], 'Maskinliste POS', null),
  ('BC18', 'Flexskab', 'Brød & bake-off', 'salg', 'maskine', 8, 400, 0.9, 0.7, 'C', '30 mA A', false, false, 0.5, 'HT01', 'bakeoff', 'fast', 1, null, null, '{}', 'Maskinliste POS', null),
  ('BC19', 'Delikøl', 'Deli', 'salg', 'koel', 1.03, 230, 0.9, 0.85, 'C', '30 mA A', true, false, 0.6, 'HT01', 'deli', 'fast', 2, null, null, ARRAY['DELIKØL'], 'Maskinliste POS', null),
  ('BC20', 'Prismærkningsanlæg', 'Deli', 'salg', 'it', 0.2, 230, 0.9, 0.5, 'B', '30 mA A', false, false, 0.9, 'HT01', 'deli', 'fast', 1, null, null, '{}', 'Marianne SB', null),
  ('BC21', 'PC i deli', 'Deli', 'salg', 'it', 0.3, 230, 0.9, 0.7, 'B', '30 mA A', false, false, 0.9, 'HT01', 'deli', 'fast', 1, null, null, '{}', 'Marianne SB', null),
  ('MC1', 'Merrychef speed-oven', 'Brød & bake-off', 'salg', 'maskine', 6, 230, 0.95, 0.5, 'D', '30 mA A', false, false, 0.5, 'HT01', 'bakeoff', 'fast', 1, null, null, ARRAY['MERRYCHEF'], 'Maskinliste POS', null),
  ('SL7a', 'Kogebord glaskeramisk, 4 zoner', 'Slagter', 'slagter', 'maskine', 9, 400, 0.95, 0.5, 'D', '30 mA A', false, false, 0.1, 'HT01', 'slagter', 'fast', 1, 20, 'Electrolux NB serie 700', '{}', 'Slagter-maskinliste SL7a', null),
  ('SL9', 'Friture', 'Slagter', 'slagter', 'maskine', 16.5, 400, 0.95, 0.55, 'D', '30 mA A', false, false, 0.1, 'HT01', 'slagter', 'fast', 1, null, null, '{}', 'Slagter-maskinliste', null),
  ('SL10', 'Kipsteger', 'Slagter', 'slagter', 'maskine', 1.8, 400, 0.9, 0.4, 'C', '30 mA A', false, false, 0.1, 'HT01', 'slagter', 'fast', 1, null, null, '{}', 'Slagter-maskinliste', null),
  ('SL11', 'Konvektionsovn', 'Slagter', 'slagter', 'maskine', 11.1, 400, 0.95, 0.6, 'D', '30 mA A', false, false, 0.1, 'HT01', 'slagter', 'fast', 2, 20, 'Coba/Electrolux, dobbeltovn i rack', '{}', 'Slagter-maskinliste SL11', null),
  ('SL12', 'Opvaskemaskine (Jeros)', 'Slagter', 'slagter', 'maskine', 8.5, 400, 0.95, 0.4, 'C', '30 mA A', false, false, 0.1, 'HT01', 'slagter', 'fast', 1, 13, 'Jeros 9110', '{}', 'Slagter-maskinliste SL12', null),
  ('SL15', 'Skumrenseanlæg', 'Slagter', 'slagter', 'maskine', 1.15, 230, 0.9, 0.2, 'C', '30 mA A', false, false, 0, 'HT01', 'slagter', 'fast', 1, 10, 'Ecolab S510', '{}', 'Slagter-maskinliste SL15', null),
  ('SL18', 'Vakuumpakker', 'Slagter', 'slagter', 'maskine', 3.5, 400, 0.9, 0.4, 'C', '30 mA A', false, false, 0.1, 'HT01', 'slagter', 'fast', 1, null, null, '{}', 'Slagter-maskinliste', null),
  ('SL19', 'Arbejdsstation slagter (EDB + alm.)', 'Slagter', 'slagter', 'it', 0.4, 230, 0.9, 0.7, 'B', '30 mA A', false, false, 0.1, 'HT01', 'slagter', 'fast', 1, null, null, '{}', 'Marianne SB', null),
  ('SL21', 'Pakkedispenser/pakkebord', 'Slagter', 'slagter', 'maskine', 0.78, 230, 0.9, 0.3, 'C', '30 mA A', false, false, 0.1, 'HT01', 'slagter', 'fast', 1, 10, 'Sibola pakkebord model 83', '{}', 'Slagter-maskinliste SL21', null),
  ('SL23a', 'Prismærkerboks', 'Slagter', 'slagter', 'it', 0.14, 230, 0.9, 0.5, 'B', '30 mA A', false, false, 0.1, 'HT01', 'slagter', 'fast', 1, 10, 'Digi DPS 5602 M', '{}', 'Slagter-maskinliste SL23a', 'Egen elgruppe + PDS kat. 5 til switch'),
  ('SL25', 'Kølebord slagter', 'Slagter', 'slagter', 'koel', 1, 230, 0.9, 0.85, 'C', '30 mA A', true, false, 0.3, 'HT01', 'slagter', 'fast', 2, 10, 'ViboCold', '{}', 'Slagter-maskinliste SL25', null),
  ('SL31', 'Pålægsmaskine', 'Slagter', 'slagter', 'maskine', 0.4, 230, 0.9, 0.3, 'C', '30 mA A', false, false, 0.1, 'HT01', 'slagter', 'fast', 1, 10, 'Myhrwold Bizerba GSP H', '{}', 'Slagter-maskinliste SL31', null),
  ('SL34', 'Bordhakker', 'Slagter', 'slagter', 'maskine', 1.5, 400, 0.85, 0.4, 'C', '30 mA A', false, false, 0.1, 'HT01', 'slagter', 'fast', 1, null, null, '{}', 'Slagter-maskinliste', null),
  ('SL17', 'Dispositionsstik 230 V, slagter', 'Slagter', 'slagter', 'stik', 0.2, 230, 0.9, 0.3, 'B', '30 mA A', false, false, 0.1, 'HT01', 'slagter', 'fast', 6, 10, null, '{}', 'Slagter-maskinliste SL17', 'Maskinliste SL17: 6 stk. CE/alm., i alt 0,9 kW pr. gruppe, placeret underkant loft'),
  ('SL36', 'Dispositionsstik 400 V slagter', 'Slagter', 'slagter', 'stik', 3.6, 400, 0.9, 0.3, 'C', '30 mA A', false, false, 0.1, 'HT01', 'slagter', 'fast', 3, null, null, '{}', 'Slagter-maskinliste', null),
  ('SL28', 'Fluefanger', 'Slagter', 'slagter', 'stik', 0.06, 230, 0.9, 1, 'B', '30 mA A', false, false, 0, 'HT01', 'slagter', 'fast', 1, 10, null, '{}', 'Slagter-maskinliste SL28', null),
  ('K3', 'CO₂-kondensaggregat, central køl', 'Køl & frost', 'teknik', 'koel', 12, 400, 0.85, 0.9, 'C', '300 mA B', true, false, 0, 'UT02 – Køl', 'centralkoel', 'kwm2salg', 0.0171, null, null, '{}', 'Køleleverandør, skaleret', 'Type B RCD (frekvensomformer)'),
  ('K4', 'Frostrum, kompressor', 'Køl & frost', 'teknik', 'koel', 4, 400, 0.85, 0.9, 'C', '300 mA B', true, false, 0, 'UT02 – Køl', 'centralkoel', 'fast', 1, null, null, ARRAY['FROSTRUM'], 'Byggeprogram §8', null),
  ('K5', 'Kølerum, kompressor', 'Køl & frost', 'teknik', 'koel', 3, 400, 0.85, 0.9, 'C', '300 mA B', true, false, 0, 'UT02 – Køl', 'centralkoel', 'fast', 1, null, null, ARRAY['KØLERUM','MEJERIKØL'], 'Byggeprogram §8', null),
  ('K6', 'CO₂ dryeksp.-modul (styring)', 'Køl & frost', 'teknik', 'koel', 2.5, 400, 0.85, 0.7, 'C', '300 mA B', true, false, 0, 'UT02 – Køl', 'centralkoel', 'fast', 1, null, null, '{}', 'Køleleverandør', null),
  ('K7', 'Gulvvarme + alarm i køle-/frostrum', 'Køl & frost', 'teknik', 'koel', 0.8, 230, 1, 0.5, 'C', '30 mA A', false, false, 0, 'UT02 – Køl', 'centralkoel', 'fast', 1, null, null, '{}', 'Maskininstallation', null),
  ('V1', 'Ventilation AHU-1 (Unic-Air)', 'HVAC & varmepumper', 'teknik', 'hvac', 9, 400, 0.85, 0.85, 'C', 'RCBO B', false, true, 0.1, 'HT01', null, 'kwm2salg', 0.0129, null, null, '{}', 'Unic-Air datablad, skaleret', null),
  ('V0', 'Ventilation AHU-2, kogerum', 'HVAC & varmepumper', 'teknik', 'hvac', 2.5, 400, 0.85, 0.8, 'C', 'RCBO B', false, true, 0.1, 'HT01', 'slagter', 'fast', 1, null, null, '{}', 'Unic-Air datablad', null),
  ('V2', 'Varmepumpe/komfortkøl (R32 Wind-Free)', 'HVAC & varmepumper', 'teknik', 'hvac', 6, 400, 0.85, 0.75, 'C', 'RCBO B', false, true, 0, 'HT01', 'varmepumpe', 'm2salg', 350, null, null, '{}', 'Datablad varmepumper', 'Bimåler ABB B23 pr. stk. (M-Bus)'),
  ('L1', 'Belysning salgsareal 3500 K', 'Belysning', 'salg', 'lys', 6.5, 230, 1, 1, 'B', '30 mA A', true, false, 0.95, 'HT01', null, 'wm2salg', 9, null, null, '{}', 'Byggeprogram §3.2', null),
  ('L2', 'Belysning personale + lager 4000 K', 'Belysning', 'lager', 'lys', 2, 230, 1, 0.85, 'B', '30 mA A', false, false, 0, 'HT01', null, 'wm2lager', 8, null, null, '{}', 'Byggeprogram §3.2', null),
  ('L3', 'Facade + P-plads', 'Belysning', 'udv', 'lys', 2, 400, 1, 1, 'B', '30 mA A', false, false, 0, 'HT01', null, 'fast', 1, null, null, '{}', 'El-projekt E-1/E-3', null),
  ('L4', 'Nød- og panikbelysning (central batteri)', 'Belysning', 'salg', 'lys', 1.2, 230, 1, 1, 'B', '–', true, false, 0.5, 'HT01', null, 'fast', 1, null, null, '{}', 'DS/EN 1838', 'Egen kritisk gruppe uden RCD'),
  ('LA1', 'Pappresse (32 A CEE)', 'Lager & varemodtag.', 'lager', 'maskine', 4, 400, 0.85, 0.3, 'C', '30 mA A', false, false, 0, 'HT01', null, 'fast', 1, null, null, ARRAY['PAPPRESSER'], 'Byggeprogram §4.4.2.11', null),
  ('LA2', 'Plastpresse', 'Lager & varemodtag.', 'lager', 'maskine', 4, 400, 0.85, 0.3, 'C', '30 mA A', false, false, 0, 'HT01', null, 'fast', 1, null, null, ARRAY['PLASTPRESSER'], 'El-effektoversigt', null),
  ('LA3', 'Ladestation, stabler', 'Lager & varemodtag.', 'lager', 'maskine', 3, 230, 0.95, 0.4, 'C', '30 mA A', false, false, 0, 'HT01', null, 'fast', 1, null, null, '{}', 'El-effektoversigt', null),
  ('LA7', 'Flaskeautomat (nyt anlæg)', 'Lager & varemodtag.', 'lager', 'maskine', 3.5, 400, 0.9, 0.5, 'C', '30 mA B', false, false, 0, 'HT01', 'flaskeautomat', 'fast', 1, null, null, ARRAY['FLASKEAUTOMAT'], 'Byggeprogram §4.4.2.9', '1×400 V + 2×230 V. Type B pga. DC-lækstrøm'),
  ('LA11', 'Varemodtagelse EDB + PC + vægt', 'Lager & varemodtag.', 'lager', 'it', 0.5, 230, 0.9, 0.7, 'B', '30 mA A', false, false, 0, 'HT01', null, 'fast', 1, null, null, '{}', 'El-effektoversigt', null),
  ('LA12', 'Postudlevering EDB + vægt', 'Lager & varemodtag.', 'lager', 'it', 0.4, 230, 0.9, 0.5, 'B', '30 mA A', false, false, 0, 'HT01', null, 'fast', 1, null, null, '{}', 'El-effektoversigt', null),
  ('LA13', 'Frokoststue (køl/mikro/opvask)', 'Personale', 'personale', 'maskine', 4.5, 230, 0.95, 0.4, 'C', '30 mA A', false, false, 0, 'HT01', null, 'fast', 1, null, null, '{}', 'El-effektoversigt', null),
  ('LA14', 'Gulvvaskemaskine (opladning)', 'Lager & varemodtag.', 'lager', 'maskine', 1.5, 230, 0.95, 0.3, 'C', '30 mA A', false, false, 0, 'HT01', null, 'fast', 1, null, null, '{}', 'El-effektoversigt', null),
  ('LA15', 'Rullegitre, motor', 'Lager & varemodtag.', 'lager', 'maskine', 0.75, 230, 0.85, 0.05, 'C', '30 mA A', false, false, 0, 'HT01', null, 'fast', 2, null, null, '{}', 'El-effektoversigt', null),
  ('LA16', 'Toiletrum, stik + håndtørrer', 'Personale', 'personale', 'stik', 1.6, 230, 1, 0.2, 'C', '30 mA A', false, false, 0, 'HT01', null, 'fast', 1, null, null, '{}', 'Marianne SB', null),
  ('D1', 'POS + SCO, UPS-udgang', 'IT, POS & sikring', 'salg', 'it', 3.5, 230, 0.9, 0.9, 'B', '30 mA A', true, false, 0.9, 'HT01', null, 'fast', 1, null, null, '{}', 'Byggeprogram §3.2', 'Kritisk – egen RCBO, ej fælles med komfortlast'),
  ('D2', 'IT-rack + netværk', 'IT, POS & sikring', 'teknik', 'it', 2, 230, 0.9, 1, 'B', '30 mA A', true, false, 0.3, 'HT01', null, 'fast', 1, null, null, '{}', 'Byggeprogram §3.2', 'Egen RCBO + SPD kl. III'),
  ('D4', 'Rengøringsstik + almen kraft', 'IT, POS & sikring', 'salg', 'stik', 3, 400, 0.9, 0.25, 'C', '30 mA A', false, false, 0.2, 'HT01', null, 'fast', 1, null, null, '{}', 'Byggeprogram §4.3', null),
  ('S1', 'ABA brandcentral', 'IT, POS & sikring', 'teknik', 'it', 0.4, 230, 0.95, 1, 'B', '30 mA A', true, false, 0.2, 'HT01', null, 'fast', 1, null, null, '{}', 'Byggeprogram §4.4.2.14', 'Egen rødmærket gruppe'),
  ('S2', 'ABDL adgangskontrol', 'IT, POS & sikring', 'teknik', 'it', 0.3, 230, 0.95, 1, 'B', '30 mA A', true, false, 0.2, 'HT01', null, 'fast', 1, null, null, '{}', 'Byggeprogram §4.4.2.12', null),
  ('S3', 'AIA/tyverialarm', 'IT, POS & sikring', 'teknik', 'it', 0.3, 230, 0.95, 1, 'B', '30 mA A', true, false, 0.2, 'HT01', null, 'fast', 1, null, null, '{}', 'El-effektoversigt', null),
  ('S4', 'Videoovervågning + NVR', 'IT, POS & sikring', 'teknik', 'it', 0.4, 230, 0.9, 1, 'B', '30 mA A', true, false, 0.2, 'HT01', null, 'fast', 1, null, null, '{}', 'El-effektoversigt', null),
  ('S5', 'Talevarsling/PA-anlæg', 'IT, POS & sikring', 'teknik', 'it', 0.3, 230, 0.9, 0.5, 'B', '30 mA A', false, false, 0.2, 'HT01', null, 'fast', 1, null, null, '{}', 'El-effektoversigt', null),
  ('S6', 'Hjertestarter, udvendig (RCBO)', 'Udvendigt', 'udv', 'it', 0.2, 230, 1, 1, 'B', 'RCBO 30 mA', true, false, 0, 'HT01', null, 'fast', 1, null, null, '{}', 'El-effektoversigt', null),
  ('S7', 'Varesikring/gates', 'IT, POS & sikring', 'salg', 'it', 0.3, 230, 0.9, 1, 'B', '30 mA A', false, false, 0.5, 'HT01', null, 'fast', 1, null, null, '{}', 'Marianne SB', null),
  ('CTS1', 'CTS-tavle (Niagara 4) + servicestik', 'CTS & bimåling', 'teknik', 'it', 1.5, 400, 0.9, 0.5, 'C', '30 mA A', true, false, 0.1, 'UT01 – CTS', null, 'fast', 1, null, null, '{}', 'Byggeprogram §6', 'SPD kl. II + potentialfri melding til CTS'),
  ('EL1', 'Vareelevator', 'Lager & varemodtag.', 'lager', 'maskine', 7.5, 400, 0.85, 0.3, 'D', '30 mA A', false, false, 0, 'HT01', 'elevator', 'fast', 1, null, null, '{}', 'Byggeprogram', 'Startspids 5–6 × I_n, egen elevatortavle'),
  ('EV1', 'Ladestander el-bil 22 kW', 'Udvendigt', 'udv', 'maskine', 22, 400, 1, 0.6, 'C', '30 mA B', false, true, 0, 'HT01', 'ladestander', 'ladestander', null, null, null, '{}', 'Byggeprogram', 'Type B RCD, egen bimåler, lastbalancering anbefales'),
  ('SPR', 'Sprinklerpumpe (test)', 'Teknik', 'teknik', 'maskine', 30, 400, 0.85, 0.05, 'D', '30 mA A', false, false, 0, 'HT01', 'sprinkler', 'fast', 1, null, null, '{}', 'Marianne SB', null),
  ('PV', 'Solcelleanlæg, invertere', 'Solceller (PV)', 'tag', 'pv', -0.8, 400, 1, 1, 'C', '300 mA B', false, true, 0, 'HT01', 'pv', 'pv', null, null, null, '{}', 'Kravspec. solceller §6', 'Produktion – modregnes ikke i hovedsikring. PSO-målerfelt reserveres')
on conflict (id) do update set navn=excluded.navn, kw=excluded.kw, df=excluded.df, cosphi=excluded.cosphi, kilde=excluded.kilde, opdateret=now();
